### Checking employee leave eligibility

GET http://localhost:3000/leave/eligibility/2


### Initialize leave policies

POST http://localhost:3000/leave/initialize-policies
Content-Type: application/json

{}


### Initialize Employee leave history

POST http://localhost:3000/leave/initialize-history/2
Content-Type: application/json

{
    "lastLeaveEndDate":"2024-03-01",
    "initialBalance": 10
}

### Create a new leave

POST http://localhost:3000/leave/new-leave 
Content-Type: application/json

{
    "employeeId":1,
    "leaveType":"regular",
    "startDate":"2025-04-20"
}