### Creating an employee

POST http://localhost:3000/employees
Content-Type: application/json

{
    "fullName":"Joh Doe",
    "role":"Manager",
    "department":"Information Technology",
    "salary":2300,
    "dateOfBirth":"2000-04-05",
    "dateOfHire":"2025-03-26",
    "attendance":"present",
    "category":"CC1",
    "contractType":"CDI",
    "noMatricule":"P004ER2352245I"
}




### Listing all employees

GET http://localhost:3000/employees/all




### Updating an existing employee

PATCH  http://localhost:3000/employees/2 
Content-Type: application/json

{
    "dateOfHire":"2020-02-21"
}


### Finding one employee

GET http://localhost:3000/employees/1


### Deleting an employee

DELETE http://localhost:3000/employees/2

### updating employee attendance

PATCH  http://localhost:3000/employees/1/attendance
Content-Type: application/json

{
    "attendance":"onleave"
}