### Creating an employee

POST http://localhost:3000/employees
Content-Type: application/json

{
    "fullName":"Yannick Zahinda",
    "role":"Developer",
    "department":"Information Technology",
    "salary":1500,
    "dateOfBirth":"2000-04-05",
    "dateOfHire":"2025-03-26"
}

### Listing all employees

GET http://localhost:3000/employees/all