### Creating an employee

POST http://localhost:3000/employees
Content-Type: application/json

{
    "fullName":"Esther Katula",
    "role":"DIrectrice Financiere",
    "department":"Finances",
    "salary":1000,
    "dateOfBirth":"2001-07-05",
    "dateOfHire":"2025-01-01",
    "attendance":"present",
    "category":"CC2",
    "contractType":"CDI",
    "noMatricule":"P074ER2350045I"
}




### Listing all employees

GET http://localhost:3000/employees/all




### Updating an existing employee

PATCH  http://localhost:3000/employees/4
Content-Type: application/json

{
    "category":"HQ"
}


### Finding one employee

GET http://localhost:3000/employees/4


### Deleting an employee

DELETE http://localhost:3000/employees/2

### updating employee attendance

PATCH  http://localhost:3000/employees/1/attendance
Content-Type: application/json

{
    "attendance":"onleave"
}